# Generated by Django 3.0.5 on 2020-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleWebpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_cmd', models.TextField()),
                ('raw_history', models.TextField()),
            ],
        ),
    ]
