# Generated by Django 3.0.5 on 2020-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlewebpage',
            name='raw_history',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
