# Generated by Django 3.0.5 on 2020-12-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201206_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlewebpage',
            name='raw_cmd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
