# Generated by Django 3.0.5 on 2020-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201206_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlewebpage',
            name='description_cmd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
