# Generated by Django 3.0.5 on 2020-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_controlewebpage_description_cmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteCMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_cmd', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlewebpage',
            name='raw_cmd',
        ),
    ]
