# Generated by Django 3.0.8 on 2020-12-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201206_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('innerWidth', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
            ],
        ),
    ]
